BUNDLE_INSTALL_DIR=$(GNUSTEP_INSTALLATION_DIR)/Library/Bundles/Paje
GNUSTEP_MAKEFILES = $(GNUSTEP_SYSTEM_ROOT)/Makefiles
include $(GNUSTEP_MAKEFILES)/common.make

ImbricationFilter_PRINCIPAL_CLASS = InsetLimit

BUNDLE_NAME = ImbricationFilter

ADDITIONAL_INCLUDE_DIRS = -I../General.bproj

ImbricationFilter_RESOURCE_FILES = InsetLimit.gorm

ImbricationFilter_OBJC_FILES = InsetLimit.m

ImbricationFilter_HEADER_FILES = InsetLimit.h

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
