/*
    Copyright (c) 1998--2006 Benhur Stein
    
    This file is part of Pajé.

    Pajé is free software; you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    Pajé is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
    for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Pajé; if not, write to the Free Software Foundation, Inc.,
	51 Franklin Street, Fifth Floor, Boston, MA 02111 USA.
*/


/* Do not edit. File generated by rastro_generate. */

#ifndef _RASTRO_JRastro_rastros_H_
#define _RASTRO_JRastro_rastros_H_

#include "rastro_public.h"
#include "rastro_private.h"

void rst_event_i_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0);
#define rst_event_i(type, i0) rst_event_i_ptr(RST_PTR, type, i0)
void rst_event_ii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1);
#define rst_event_ii(type, i0, i1) rst_event_ii_ptr(RST_PTR, type, i0, i1)
void rst_event_is_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int8_t *s0);
#define rst_event_is(type, i0, s0) rst_event_is_ptr(RST_PTR, type, i0, s0)
void rst_event_isii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int8_t *s0, u_int32_t i1, u_int32_t i2);
#define rst_event_isii(type, i0, s0, i1, i2) rst_event_isii_ptr(RST_PTR, type, i0, s0, i1, i2)
void rst_event_isiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int8_t *s0, u_int32_t i1, u_int32_t i2, u_int32_t i3);
#define rst_event_isiii(type, i0, s0, i1, i2, i3) rst_event_isiii_ptr(RST_PTR, type, i0, s0, i1, i2, i3)
void rst_event_liis_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0, u_int32_t i0, u_int32_t i1, u_int8_t *s0);
#define rst_event_liis(type, l0, i0, i1, s0) rst_event_liis_ptr(RST_PTR, type, l0, i0, i1, s0)
void rst_event_lis_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0, u_int32_t i0, u_int8_t *s0);
#define rst_event_lis(type, l0, i0, s0) rst_event_lis_ptr(RST_PTR, type, l0, i0, s0)

#endif
