/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lsc_JRastro_Instru */

#ifndef _Included_org_lsc_JRastro_Instru
#define _Included_org_lsc_JRastro_Instru
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lsc_JRastro_Instru
 * Method:    func_init
 * Signature: (Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_org_lsc_JRastro_Instru_func_1init
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_lsc_JRastro_Instru
 * Method:    func_newArray
 * Signature: (Ljava/lang/Object;Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_org_lsc_JRastro_Instru_func_1newArray
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_lsc_JRastro_Instru
 * Method:    func
 * Signature: (Ljava/lang/Object;Ljava/lang/Thread;I)V
 */
JNIEXPORT void JNICALL Java_org_lsc_JRastro_Instru_func
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     org_lsc_JRastro_Instru
 * Method:    func_entry
 * Signature: (Ljava/lang/Thread;I)V
 */
JNIEXPORT void JNICALL Java_org_lsc_JRastro_Instru_func_1entry
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lsc_JRastro_Instru
 * Method:    func_exit
 * Signature: (Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_org_lsc_JRastro_Instru_func_1exit
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
